name: SkullSecurity
title: SkullSecurity Blog
email: your-email@example.com
description: Adventures In Security
url: "https://blog.skullsecurity.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: iagox86
github_username:  iagox86
logo: /assets/skullsecurity.jpg

paginate: 20
excerpt_separator: '<!--more-->'

collections:
  authors:
    output: true
  categories:
    output: true
  widgets:
    output: true
  posts:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
