name: SkullSecurity
title: SkullSecurity Blog
email: your-email@example.com
description: Adventures In Security
url: "https://blog.skullsecurity.org" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/skullsecurity.jpg

paginate: 20
excerpt_separator: '<!--more-->'

# Mastodon comment settings
comments:
  host: infosec.exchange
  username: skullsecurity

collections:
  authors:
    output: true
  categories:
    output: true
  widgets:
    output: true
  posts:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

feed:
  path: /feed
