name: SkullSecurity
title: SkullSecurity Blog
email: your-email@example.com
description: Adventures In Security
url: "https://blog.skullsecurity.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: iagox86
github_username:  iagox86

paginate: 5
excerpt_separator: '<!--more-->'

collections:
  authors:
    output: true
  categories:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
